repos:
    - repo: local
      hooks:
        - id: isort
          name: isort
          entry: poetry run isort -c finlang/
          language: system
          always_run: true
          pass_filenames: false
          
        - id: pylint
          name: pylint
          entry: poetry run pylint finlang/ --max-line-length=120 --ignore=tests --fail-under=9
          language: system
          always_run: true
          pass_filenames: false
          
        - id: pytest
          name: pytest
          entry: poetry run pytest -W ignore finlang/tests
          language: system
          always_run: false
          pass_filenames: false
